services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: construction_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: app123
      DB_NAME: construction_db
      DB_PORT: 3306
    depends_on:
      - mysql

  frontend:
    build: ../construction-frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  jenkins:
    build: ./jenkins
    container_name: jenkins-container
    ports:
    - "8082:8080"
    - "50000:50000"
    volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    user: root
    dns:
    - 8.8.8.8
    - 8.8.4.4
# ✅ OUTSIDE services (VERY IMPORTANT)
volumes:
  jenkins_home: