pipeline {
    agent any

    environment {
        IMAGE_NAME = "construction-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh 'npm install'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME:${env.BRANCH_NAME} .'
            }
        }

        stage('Run') {
            steps {
                sh 'docker run -d -p 3000:3000 $IMAGE_NAME:${env.BRANCH_NAME}'
            }
        }
    }
}