pipeline {
    agent any

    environment {
        IMAGE_NAME = "construction-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                bat 'cd construction-backend && npm install'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:%BRANCH_NAME% construction-backend'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 5000:5000 %IMAGE_NAME%:%BRANCH_NAME%'
            }
        }

        stage('List Images (Demo)') {
            steps {
                bat 'docker images'
            }
        }
    }
}